version: '3.8'
services:
  harvestinn:
    build: .
    ports:
      - "8080:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes:
      - ./database/database.sqlite:/var/www/html/database/database.sqlite
      - ./storage:/var/www/html/storage
    restart: unless-stopped
